### ISSUE TITLE
https://github.com/KircheNeuenburg/ldaporg/issues/38

### ISSUE THREAD

**Issue by p-bo** [Rello/BlockScores-App#2]
Hello,
would it be possible to follow instructions on:

https://nextcloudappstore.readthedocs.io/en/latest/restapi.html#delete-an-app

and remove your past app:

https://apps.nextcloud.com/apps/blockscores

and help through this to tidy up the Nextcloud App store (most importantly it clutters apps catalogue in every Nextcloud instance) a bit please?

Thanks and have a nice day

**Comment by Rello** [comment]
done

**Comment by p-bo** [comment]
Many thanks for your cooperation! :-)
